 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pupil_measurements", type: :request do
  # PupilMeasurement. As you add validations to PupilMeasurement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PupilMeasurement.create! valid_attributes
      get pupil_measurements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pupil_measurement = PupilMeasurement.create! valid_attributes
      get pupil_measurement_url(pupil_measurement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pupil_measurement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pupil_measurement = PupilMeasurement.create! valid_attributes
      get edit_pupil_measurement_url(pupil_measurement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PupilMeasurement" do
        expect {
          post pupil_measurements_url, params: { pupil_measurement: valid_attributes }
        }.to change(PupilMeasurement, :count).by(1)
      end

      it "redirects to the created pupil_measurement" do
        post pupil_measurements_url, params: { pupil_measurement: valid_attributes }
        expect(response).to redirect_to(pupil_measurement_url(PupilMeasurement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PupilMeasurement" do
        expect {
          post pupil_measurements_url, params: { pupil_measurement: invalid_attributes }
        }.to change(PupilMeasurement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pupil_measurements_url, params: { pupil_measurement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pupil_measurement" do
        pupil_measurement = PupilMeasurement.create! valid_attributes
        patch pupil_measurement_url(pupil_measurement), params: { pupil_measurement: new_attributes }
        pupil_measurement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pupil_measurement" do
        pupil_measurement = PupilMeasurement.create! valid_attributes
        patch pupil_measurement_url(pupil_measurement), params: { pupil_measurement: new_attributes }
        pupil_measurement.reload
        expect(response).to redirect_to(pupil_measurement_url(pupil_measurement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pupil_measurement = PupilMeasurement.create! valid_attributes
        patch pupil_measurement_url(pupil_measurement), params: { pupil_measurement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pupil_measurement" do
      pupil_measurement = PupilMeasurement.create! valid_attributes
      expect {
        delete pupil_measurement_url(pupil_measurement)
      }.to change(PupilMeasurement, :count).by(-1)
    end

    it "redirects to the pupil_measurements list" do
      pupil_measurement = PupilMeasurement.create! valid_attributes
      delete pupil_measurement_url(pupil_measurement)
      expect(response).to redirect_to(pupil_measurements_url)
    end
  end
end
